package com.egmm.maintenance.entity;

public enum NatureTravauxType {
    REPARATION,
    DEPANNAGE,
    ENTRETIEN_EXCEPTIONNEL,
    AMELIORATION_PRODUCTION,
    ENTRETIEN_PREVENTIF,
    TRAVAUX_NEUFS,
    AMELIORATION_HYGIENE_SECURITE,
    AMELIORATION_MAINTENANCE
}